site_name: LBL Chemical Reaction Network

nav:
  - About: 'index.md'
  - Quickstart: 'quickstart.md'
  - Examples: 'examples.md'
  - License: 'license.md'
  - Contact: 'contact.md'
  - API Docs: 'api-docs.md'

theme:
  name: mkdocs
  nav_style: dark

extra_css:
  - css/extra.css

site_dir: site/
